---
title: "projectPresentation"
author: "Xixi"
date: "2023-02-23"
output: html_document
---

# Final Paper 

Many cities are known for their cherry blossom viewing sites, and every year, thousands of tourists visit those places to watch cherry blossoms. However, many tourists on social media complained that either they went to the viewing sites, but the cherry had not bloomed, or the cherry had already started to wither. Two of our team members had this experience themselves. Thus, knowing the cherry blossom dates is beneficial for the tourists to arrange their trips, helping them save money and time. 

In this paper, we explore the 6 predictors of daily average temperature, humidity, pressure, wind speed, daily precipitation, and modified accumulated temperature, utilizing *various models* to predict cherry blossom dates at Washington, D.C. (USA), Kyoto (Japan), Liestal-Weideli (Switzerland) and Vancouver, BC (Canada). 

# Data

Instead of using the cherry blossom date, we use blossom day (from Jan 1 of each year) as our dependent variable. We also scraped weather data such as daily average temperature, humidity, pressure, wind speed, daily precipitation from [The Weather Channel](https://weather.com/?Goto=Redirected) using JavaScript. Inspired by the paper [The prediction model of initial flowering based on accumulated temperature of different species peach in Longquanyi](https://dl.acm.org/doi/pdf/10.1145/3321408.3326690), we create a new variable called effective accumulated temperature, which measures 


effective accumulated temperature

When the effective accumulated temperature of peach blossoms reaches the accumulated temperature threshold, the corresponding date is the initial flowering period of the peach. 

the accumulated temperature thresholds are different for 4 sites

```{r}


```


# Methodology


# Results


# Conclusion


# References 
